# Generated by Django 5.2.4 on 2025-07-06 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfclient',
            name='name',
            field=models.CharField(default='unknown client', max_length=128),
        ),
        migrations.AddField(
            model_name='sfsupportagent',
            name='name',
            field=models.CharField(default='unknown agent', max_length=128),
        ),
        migrations.AddField(
            model_name='sfticket',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainWebApp.sfclient'),
        ),
        migrations.AddField(
            model_name='sfticket',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sfticket',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainWebApp.sfsupportagent'),
        ),
        migrations.AddField(
            model_name='sfticket',
            name='titre',
            field=models.CharField(default='new ticket', max_length=128),
        ),
        migrations.AddField(
            model_name='sfticket',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainWebApp.sfworkflow'),
        ),
        migrations.CreateModel(
            name='SfRagMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(default='message')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainWebApp.sfsupportagent')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainWebApp.sfticket')),
            ],
            options={
                'db_table': 'sfix_rag_message',
            },
        ),
    ]
