# Generated by Django 5.2.4 on 2025-07-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebApp', '0002_sfclient_name_sfsupportagent_name_sfticket_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfragmessage',
            name='date_message',
            field=models.DateTimeField(null=True),
        ),
    ]
