# Generated by Django 5.2.4 on 2025-07-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebApp', '0003_sfragmessage_date_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfragmessage',
            name='date_message',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
