# Generated by Django 5.2.4 on 2025-07-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebApp', '0004_alter_sfragmessage_date_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfworkflow',
            name='name',
            field=models.CharField(default='new workflow', max_length=128),
        ),
    ]
