# Generated by Django 5.2.4 on 2025-07-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebApp', '0005_sfworkflow_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sfticket',
            old_name='titre',
            new_name='title',
        ),
    ]
