# Generated by Django 5.2.4 on 2025-07-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebApp', '0006_rename_titre_sfticket_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sfragmessage',
            old_name='staff',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='sfragmessage',
            old_name='date_message',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='sfragmessage',
            old_name='message_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='sfticket',
            old_name='date_creation',
            new_name='created',
        ),
    ]
